//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public string bID { get; set; }
        public string oID { get; set; }
        public string cID { get; set; }
        public string eID { get; set; }
        public Nullable<System.DateTime> BILLDATE { get; set; }
    
        public virtual ORDER ORDER { get; set; }
        public virtual CLIENT CLIENT { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
